apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: portal-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: portal-frontend
    spec:
      containers:
      - name: app
        image: ghcr.io/modusintegration/finance-portal-settlements
        ports:
        - containerPort: 3000
