apiVersion: v1
kind: Service
metadata:
  name: portal-frontend
  labels:
    app.kubernetes.io/name: portal-frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app.kubernetes.io/name: portal-frontend
