apiVersion: v1
kind: Service
metadata:
  name: portal-backend
  labels:
    app.kubernetes.io/name: portal-backend
spec:
  ports:
  - port: 80
    targetPort: 3002
  selector:
    app.kubernetes.io/name: portal-backend
