apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: portal-backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: portal-backend
    spec:
      containers:
      - name: app
        image: mojaloop/finance-portal-backend-service
        ports:
        - containerPort: 3002
        envFrom:
        - configMapRef:
            name: portal-backend
