apiVersion: batch/v1
kind: Job
metadata:
  name: wso2is-populate
  labels:
    app.kubernetes.io/name: wso2is-populate
spec:
  # This shouldn't matter, the job should be idempotent, but we'll constrain it anyway
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wso2is-populate
    spec:
      containers:
      - name: job
        image: ghcr.io/mojaloop/wso2is-populate:latest
      restartPolicy: OnFailure
