apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2is
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wso2is
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wso2is
    spec:
      containers:
      - name: app
        image: wso2/wso2is-km:5.7.0
        ports:
        - containerPort: 9443
