resources:
- ../manifests/wso2is
- ../manifests/wso2is-populate
- github.com/partiallyordered/mojaloop-kustomize/base/portal?ref=9d513da1f06b9c9554a4d3a703ed4750076c86aa

configMapGenerator:
- name: oauth-app-credentials
  literals: &oauth_creds
  - AUTH_SERVER_CLIENTKEY=fv0xZxstzo2_qVcqMRFpLI43xm8mZZ
  - AUTH_SERVER_CLIENTSECRET=CJvf1mQxQdLqWLYuNvAicRd6iBMQo5
- name: wso2is-populate
  literals:
  - WSO2_HOST=https://wso2is:9443
- name: portal-backend
  behavior: merge
  literals: *oauth_creds

patches:
- patch: |-
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: wso2is-populate
    spec:
      template:
        spec:
          containers:
          - name: job
            envFrom:
            - configMapRef:
                name: oauth-app-credentials
            - configMapRef:
                name: wso2is-populate
