name: Integration test
on: push
jobs:
  integration-test:
    timeout-minutes: 10
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install k3d
      run: |-
        curl -Lo k3d https://github.com/rancher/k3d/releases/download/v4.4.1/k3d-linux-amd64
        sudo install k3d /usr/local/bin/

    - name: Install Skaffold
      run: |-
        curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/v1.21.0/skaffold-linux-amd64
        sudo install skaffold /usr/local/bin/

    - name: Start cluster
      run: |-
        k3d cluster create \
          --kubeconfig-update-default \
          --kubeconfig-switch-context \
          --image=rancher/k3s:v1.20.5-k3s1 \
          wso2ispopulate-integration-test

    - name: Deploy
      run: skaffold run --profile integration-test-authorisation

    - name: Wait for wso2is to come up
      run: |-
        time kubectl wait --for=condition=available --timeout=180s deploy/wso2is
        time kubectl rollout status -w --timeout=180s deploy/wso2is

    - name: Print WSO2 logs
      run: kubectl logs deploy/wso2is

    - name: Print resources
      run: kubectl get svc,deploy,configmap,job,pod -A

    - name: Tail job logs
      run: kubectl logs -f jobs/wso2is-populate

    - name: DNS
      run: |-
        kubectl run dnsutils --image gcr.io/kubernetes-e2e-test-images/dnsutils:1.3 --command -- sleep 1m
        kubectl wait --for=condition=ready pod/dnsutils
        time kubectl exec -it dnsutils -- nslookup kubernetes.default
        time kubectl exec -it dnsutils -- nslookup wso2is

    - name: Curl wso2is
      run: |-
        kubectl run curl --image curlimages/curl --command -- sleep 70s
        kubectl wait --for=condition=ready pod/curl
        time kubectl exec -it newestcurl -- curl -siu 'admin:admin' -k 'https://wso2is:9443'

    - name: Print resources
      run: kubectl get svc,deploy,configmap,job,pod -A

    - name: Wait for populate to complete
      run: time kubectl wait --for=condition=complete jobs/wso2is-populate
