name: "Smoke test Terraform module"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=https://github.com/NixOS/nixpkgs/archive/8e4fe32876ca15e3d5eb3ecd3ca0b224417f5f17.tar.gz
    - run: nix-env -if default.nix
    - run: terraform init terraform/
    - run:
        terraform plan \
          -var 'auth_server_clientkey="fjkdsalfjdskal3784291732841"' \
          -var 'auth_server_clientsecret="kfsdlja_327418kalfjdksalh_789"' \
          terraform/

