name: "Smoke test Terraform module"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: cachix/install-nix-action@v13
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: which terraform
    - run: nix-build
    - run: which terraform
    - run: tree "$NIX_PATH"
